In [4]:
import pandas as pd
import dateutil
import os
import glob
import matplotlib as plt
import seaborn as sns

In [5]:
def time(x):
    stepmin = x["Step"].min()
    stepmax = x["Step"].max()
    return pd.Series([stepmin, stepmax], index=["First_oc", "Last_oc"])

In [14]:
def duration(x):
    start = x.iloc[1][0]
    end = x.iloc[x["Step"].size - 1][0]
    return end - start

In [16]:
def to_minutes(x):
    return x/60

In [28]:
#Calculate the average number of cars seen per minute over all individual trips
path = '../simulation_output/output'
d = []
duration_data = []
group_durations = []
min_duration = 1
average_cars = pd.DataFrame(columns=["Duration", "Average_cars_per_minute"])
for filename in glob.glob(os.path.join(path, '*.csv')):
    try:
        data = pd.read_csv(filename, delimiter=',', header=0, encoding='ascii',index_col=False )
        total_duration = to_minutes(duration(data))
        if total_duration > min_duration:
            cars_seen = data["ID"].nunique()
            cars_p_minute = cars_seen / total_duration
            print(cars_p_minute)
            average_cars = average_cars.append({"Duration":total_duration, "Average_cars_per_minute":cars_p_minute}, 
                                               ignore_index=True)
    except(OSError):
        print("The file that was expected was not found")
average_cars

10.4269662921
4.00814663951
22.2870299309
10.3919781222
3.74822527212
5.91133004926
4.36363636364
7.08675799087
10.7692307692
7.57075471698
14.1291108404
8.97015326701
3.52045133992
32.9700690714
8.82011605416
4.12738853503
17.8319123021
12.7457627119
6.93076638282
6.06811145511
9.06211936663
9.72
3.0805134189
3.5718809373
14.3845534996
5.43689320388
3.00811010076
5.83368869936
3.37892196299
26.3583815029
4.072298045
5.01854974705
19.226519337
14.4214372716
9.23076923077
24.7756874096
21.2423873325
5.44794188862
3.11212814645
4.5665961945
17.4960380349
1.64172723386
4.8465266559
5.35931790499
8.69179600887
3.38863395694
25.9037711313
36.6614173228
10.6849315068
37.8685121107
4.96483243691
10.0872323553
1.70062001771
29.387755102
21.0108303249
2.84760845384
15.627141878
6.29737609329
7.12619300106
5.48947849954
5.44217687075
1.82136602452
12.7290260366
15.0964974982
9.49950932287
6.36787378989
5.35931790499
32.3076923077
3.89768574909
10.71863581
1.26315789474
25.5944055944
8.16373594696

     Duration  Average_cars_per_minute
0   11.125000                10.426966
1   10.229167                 4.008147
2    5.429167                22.287030
3    9.141667                10.391978
4    8.804167                 3.748225
5    3.383333                 5.911330
6    5.270833                 4.363636
7   13.687500                 7.086758
8    1.300000                10.769231
9   14.133333                 7.570755
10  10.262500                14.129111
11  15.495833                 8.970153
12  14.770833                 3.520451
13   5.429167                32.970069
14  15.079167                 8.820116
15   6.541667                 4.127389
16  10.262500                17.831912
17   7.375000                12.745763
18  11.254167                 6.930766
19  16.150000                 6.068111
20  10.262500                 9.062119
21   8.333333                 9.720000
22   7.141667                 3.080513
23  13.158333                 3.571881
24  10.358333                14.384553
25   5.150000                 5.436893
26  16.954167                 3.008110
27   9.770833                 5.833689
28  10.358333                 3.378922
29   2.162500                26.358382
..        ...                      ...
43  10.262500                 5.359318
44   5.637500                 8.691796
45  11.804167                 3.388634
46   9.612500                25.903771
47   2.645833                36.661417
48   9.733333                10.684932
49   6.020833                37.868512
50  10.070833                 4.964832
51   5.254167                10.087232
52  14.112500                 1.700620
53   4.083333                29.387755
54   4.616667                21.010830
55  11.237500                 2.847608
56  12.158333                15.627142
57   1.429167                 6.297376
58   3.929167                 7.126193
59   9.108333                 5.489478
60   5.512500                 5.442177
61   7.137500                 1.821366
62   8.641667                12.729026
63  11.658333                15.096497
64  12.737500                 9.499509
65  11.620833                 6.367874
66  10.262500                 5.359318
67   3.033333                32.307692
68  10.262500                 3.897686
69  10.262500                10.718636
70   4.750000                 1.263158
71   2.383333                25.594406
72  14.454167                 8.163736

[73 rows x 2 columns]

In [29]:
total_average = average_cars.mean()
total_average

Duration                    8.831792
Average_cars_per_minute    10.862604
dtype: float64